// کتابخانه‌ی الگوهای آماده برای «متره و برآورد» — اقلام رایج یک پروژه‌ی
// ساختمانی از صفر تا صد، دسته‌بندی‌شده، که با یک کلیک به‌عنوان یک ردیفِ
// از پیش‌پرشده (شرح + نوع محاسبه مناسب) به برآورد اضافه می‌شوند.
//
// shape یکی از این مقادیر است:
//   "area"   → مساحت ساده (طول × عرض)
//   "wall"   → دیوار با کسر بازشو (طول × ارتفاع − بازشوها)
//   "volume" → حجم (طول × عرض × ارتفاع)
//   "length" → طول خطی (برای لوله‌کشی، سیم‌کشی، کابل‌کشی)
//   "count"  → شمارشی (کلید، پریز، درب، شیرآلات و...)

export const QTO_TEMPLATE_CATEGORIES = [
  {
    id: "structure",
    label: "سازه و عمران",
    icon: "🏗️",
    items: [
      { name: "شمع‌کوبی", shape: "count" },
      { name: "خاکبرداری", shape: "volume" },
      { name: "بتن مگر", shape: "volume" },
      { name: "بتن فونداسیون", shape: "volume" },
      { name: "عایق رطوبتی فونداسیون", shape: "area" },
      { name: "بتن ستون", shape: "volume" },
      { name: "بتن سقف/دال", shape: "volume" },
      { name: "سقف تیرچه‌بلوک", shape: "area" },
      { name: "آرماتوربندی", shape: "count" },
      { name: "قالب‌بندی", shape: "area" },
      { name: "دیوار چینی آجر/بلوک", shape: "wall" },
      { name: "دیوار باربر", shape: "wall" },
    ],
  },
  {
    id: "steel-structure",
    label: "اسکلت فلزی",
    icon: "🔩",
    items: [
      { name: "ستون فلزی (وزنی)", shape: "count" },
      { name: "تیر فلزی (وزنی)", shape: "count" },
      { name: "جوشکاری اسکلت", shape: "count" },
      { name: "ضدزنگ و رنگ اسکلت فلزی", shape: "area" },
      { name: "عایق حریق اسکلت فلزی", shape: "area" },
      { name: "ورق کف‌ساز (دک استیل)", shape: "area" },
    ],
  },
  {
    id: "kitchen",
    label: "آشپزخانه و کابینت",
    icon: "🍳",
    items: [
      { name: "کابینت آشپزخانه (بالا و پایین)", shape: "length" },
      { name: "کانتر/صفحه کابینت (سنگ/کوارتز)", shape: "length" },
      { name: "هود آشپزخانه", shape: "count" },
      { name: "سینک توکار", shape: "count" },
      { name: "اجاق گاز/هاب", shape: "count" },
      { name: "کمد دیواری", shape: "length" },
    ],
  },
  {
    id: "finishing",
    label: "نازک‌کاری",
    icon: "🎨",
    items: [
      { name: "گچ و خاک دیوار", shape: "wall" },
      { name: "سفیدکاری/بندکشی", shape: "wall" },
      { name: "کاشی دیوار (آشپزخانه/سرویس)", shape: "wall" },
      { name: "سرامیک کف", shape: "area" },
      { name: "موزاییک کف", shape: "area" },
      { name: "سنگ کف/راه‌پله", shape: "area" },
      { name: "پارکت/لمینت", shape: "area" },
      { name: "کف‌پوش اپوکسی", shape: "area" },
      { name: "رنگ‌آمیزی دیوار", shape: "wall" },
      { name: "سقف کاذب کناف", shape: "area" },
      { name: "نمای بیرونی (سنگ/سرامیک نما)", shape: "wall" },
      { name: "ایزوگام پشت‌بام", shape: "area" },
      { name: "شیب‌بندی پشت‌بام", shape: "area" },
      { name: "عایق حرارتی نما", shape: "area" },
    ],
  },
  {
    id: "electrical",
    label: "برق",
    icon: "⚡",
    items: [
      { name: "کلید تک‌پل", shape: "count" },
      { name: "کلید دوپل/سه‌پل", shape: "count" },
      { name: "پریز برق معمولی", shape: "count" },
      { name: "پریز برق ارت‌دار", shape: "count" },
      { name: "لوله‌کشی برق (خرطومی/PVC)", shape: "length" },
      { name: "سیم‌کشی برق", shape: "length" },
      { name: "تابلو برق و فیوز", shape: "count" },
      { name: "چاه ارت", shape: "count" },
      { name: "چراغ/لوستر سقفی", shape: "count" },
      { name: "چراغ SMD/هالوژن توکار", shape: "count" },
      { name: "پریز آنتن/تلویزیون", shape: "count" },
      { name: "پریز تلفن/شبکه (LAN)", shape: "count" },
      { name: "زنگ اف‌اف/آیفون تصویری", shape: "count" },
      { name: "سیستم اعلام حریق", shape: "count" },
      { name: "دوربین مداربسته", shape: "count" },
      { name: "برق اضطراری/UPS", shape: "count" },
      { name: "دیزل ژنراتور", shape: "count" },
    ],
  },
  {
    id: "plumbing",
    label: "آب و شیرآلات",
    icon: "🚰",
    items: [
      { name: "لوله‌کشی آب سرد (پلی‌اتیلن/PPR)", shape: "length" },
      { name: "لوله‌کشی آب گرم", shape: "length" },
      { name: "شیر آب/شیرآلات ظرفشویی", shape: "count" },
      { name: "شیرآلات حمام/دوش", shape: "count" },
      { name: "توالت فرنگی", shape: "count" },
      { name: "توالت ایرانی", shape: "count" },
      { name: "روشویی", shape: "count" },
      { name: "سینک ظرفشویی", shape: "count" },
      { name: "آبگرمکن/پکیج آبگرم", shape: "count" },
      { name: "منبع آب (ذخیره)", shape: "count" },
      { name: "پمپ آب", shape: "count" },
      { name: "دستگاه تصفیه آب", shape: "count" },
      { name: "کنتور آب", shape: "count" },
    ],
  },
  {
    id: "sewage",
    label: "فاضلاب",
    icon: "🕳️",
    items: [
      { name: "لوله‌کشی فاضلاب (PVC)", shape: "length" },
      { name: "چاه فاضلاب/سپتیک", shape: "count" },
      { name: "کفشور", shape: "count" },
      { name: "سیفون/زانویی فاضلاب", shape: "count" },
      { name: "دریچه بازدید فاضلاب", shape: "count" },
    ],
  },
  {
    id: "gas",
    label: "گاز",
    icon: "🔥",
    items: [
      { name: "لوله‌کشی گاز (فولادی/مسی)", shape: "length" },
      { name: "علمک گاز", shape: "count" },
      { name: "کنتور گاز", shape: "count" },
      { name: "شیر گاز قطع‌کن", shape: "count" },
    ],
  },
  {
    id: "openings",
    label: "درب و پنجره",
    icon: "🚪",
    items: [
      { name: "درب داخلی چوبی", shape: "count" },
      { name: "درب ورودی واحد", shape: "count" },
      { name: "درب ورودی ساختمان", shape: "count" },
      { name: "درب ضدسرقت", shape: "count" },
      { name: "کرکره برقی پارکینگ", shape: "count" },
      { name: "پنجره آلومینیومی/UPVC", shape: "area" },
      { name: "شیشه دوجداره", shape: "area" },
      { name: "یراق‌آلات (دستگیره، قفل، لولا)", shape: "count" },
      { name: "کرکره/شاتر پنجره", shape: "area" },
      { name: "نرده و حفاظ", shape: "length" },
    ],
  },
  {
    id: "hvac",
    label: "سرمایش و گرمایش",
    icon: "❄️",
    items: [
      { name: "رادیاتور", shape: "count" },
      { name: "لوله‌کشی بخاری/رادیاتور", shape: "length" },
      { name: "پکیج شوفاژ", shape: "count" },
      { name: "کولر آبی", shape: "count" },
      { name: "کولر گازی/اسپلیت", shape: "count" },
      { name: "داکت اسپلیت و کانال‌کشی", shape: "length" },
      { name: "فن کویل", shape: "count" },
      { name: "کف‌گرمایی (لوله‌کشی زیرکف)", shape: "area" },
      { name: "چیلر", shape: "count" },
      { name: "برج خنک‌کننده", shape: "count" },
    ],
  },
  {
    id: "landscaping",
    label: "محوطه‌سازی",
    icon: "🌳",
    items: [
      { name: "آسفالت محوطه", shape: "area" },
      { name: "بتن‌ریزی محوطه", shape: "area" },
      { name: "جدول‌کشی", shape: "length" },
      { name: "فضای سبز/چمن‌کاری", shape: "area" },
      { name: "کفپوش پارکینگ", shape: "area" },
      { name: "نرده محوطه", shape: "length" },
      { name: "روشنایی محوطه (چراغ)", shape: "count" },
    ],
  },
  {
    id: "elevator-safety",
    label: "آسانسور و ایمنی",
    icon: "🛗",
    items: [
      { name: "آسانسور مسافربری", shape: "count" },
      { name: "کپسول آتش‌نشانی", shape: "count" },
      { name: "سیستم اسپرینکلر", shape: "count" },
      { name: "هیدرانت آتش‌نشانی", shape: "count" },
      { name: "پله فرار/اضطراری", shape: "count" },
      { name: "چراغ اضطراری خروج", shape: "count" },
    ],
  },
];
