// تولیدشده از lib/tools/quantityTakeoffTemplates.js وب — الگوهای آماده‌ی «متره و برآورد»
class QtoTemplate {
  final String name, shape;
  const QtoTemplate(this.name, this.shape);
}

class QtoCategory {
  final String id, label, icon;
  final List<QtoTemplate> items;
  const QtoCategory(this.id, this.label, this.icon, this.items);
}

const List<QtoCategory> qtoCategories = [
  QtoCategory('structure', 'سازه و عمران', '🏗️', [
    QtoTemplate('شمع‌کوبی', 'count'),
    QtoTemplate('خاکبرداری', 'volume'),
    QtoTemplate('بتن مگر', 'volume'),
    QtoTemplate('بتن فونداسیون', 'volume'),
    QtoTemplate('عایق رطوبتی فونداسیون', 'area'),
    QtoTemplate('بتن ستون', 'volume'),
    QtoTemplate('بتن سقف/دال', 'volume'),
    QtoTemplate('سقف تیرچه‌بلوک', 'area'),
    QtoTemplate('آرماتوربندی', 'count'),
    QtoTemplate('قالب‌بندی', 'area'),
    QtoTemplate('دیوار چینی آجر/بلوک', 'wall'),
    QtoTemplate('دیوار باربر', 'wall'),
  ]),
  QtoCategory('steel-structure', 'اسکلت فلزی', '🔩', [
    QtoTemplate('ستون فلزی (وزنی)', 'count'),
    QtoTemplate('تیر فلزی (وزنی)', 'count'),
    QtoTemplate('جوشکاری اسکلت', 'count'),
    QtoTemplate('ضدزنگ و رنگ اسکلت فلزی', 'area'),
    QtoTemplate('عایق حریق اسکلت فلزی', 'area'),
    QtoTemplate('ورق کف‌ساز (دک استیل)', 'area'),
  ]),
  QtoCategory('kitchen', 'آشپزخانه و کابینت', '🍳', [
    QtoTemplate('کابینت آشپزخانه (بالا و پایین)', 'length'),
    QtoTemplate('کانتر/صفحه کابینت (سنگ/کوارتز)', 'length'),
    QtoTemplate('هود آشپزخانه', 'count'),
    QtoTemplate('سینک توکار', 'count'),
    QtoTemplate('اجاق گاز/هاب', 'count'),
    QtoTemplate('کمد دیواری', 'length'),
  ]),
  QtoCategory('finishing', 'نازک‌کاری', '🎨', [
    QtoTemplate('گچ و خاک دیوار', 'wall'),
    QtoTemplate('سفیدکاری/بندکشی', 'wall'),
    QtoTemplate('کاشی دیوار (آشپزخانه/سرویس)', 'wall'),
    QtoTemplate('سرامیک کف', 'area'),
    QtoTemplate('موزاییک کف', 'area'),
    QtoTemplate('سنگ کف/راه‌پله', 'area'),
    QtoTemplate('پارکت/لمینت', 'area'),
    QtoTemplate('کف‌پوش اپوکسی', 'area'),
    QtoTemplate('رنگ‌آمیزی دیوار', 'wall'),
    QtoTemplate('سقف کاذب کناف', 'area'),
    QtoTemplate('نمای بیرونی (سنگ/سرامیک نما)', 'wall'),
    QtoTemplate('ایزوگام پشت‌بام', 'area'),
    QtoTemplate('شیب‌بندی پشت‌بام', 'area'),
    QtoTemplate('عایق حرارتی نما', 'area'),
  ]),
  QtoCategory('electrical', 'برق', '⚡', [
    QtoTemplate('کلید تک‌پل', 'count'),
    QtoTemplate('کلید دوپل/سه‌پل', 'count'),
    QtoTemplate('پریز برق معمولی', 'count'),
    QtoTemplate('پریز برق ارت‌دار', 'count'),
    QtoTemplate('لوله‌کشی برق (خرطومی/PVC)', 'length'),
    QtoTemplate('سیم‌کشی برق', 'length'),
    QtoTemplate('تابلو برق و فیوز', 'count'),
    QtoTemplate('چاه ارت', 'count'),
    QtoTemplate('چراغ/لوستر سقفی', 'count'),
    QtoTemplate('چراغ SMD/هالوژن توکار', 'count'),
    QtoTemplate('پریز آنتن/تلویزیون', 'count'),
    QtoTemplate('پریز تلفن/شبکه (LAN)', 'count'),
    QtoTemplate('زنگ اف‌اف/آیفون تصویری', 'count'),
    QtoTemplate('سیستم اعلام حریق', 'count'),
    QtoTemplate('دوربین مداربسته', 'count'),
    QtoTemplate('برق اضطراری/UPS', 'count'),
    QtoTemplate('دیزل ژنراتور', 'count'),
  ]),
  QtoCategory('plumbing', 'آب و شیرآلات', '🚰', [
    QtoTemplate('لوله‌کشی آب سرد (پلی‌اتیلن/PPR)', 'length'),
    QtoTemplate('لوله‌کشی آب گرم', 'length'),
    QtoTemplate('شیر آب/شیرآلات ظرفشویی', 'count'),
    QtoTemplate('شیرآلات حمام/دوش', 'count'),
    QtoTemplate('توالت فرنگی', 'count'),
    QtoTemplate('توالت ایرانی', 'count'),
    QtoTemplate('روشویی', 'count'),
    QtoTemplate('سینک ظرفشویی', 'count'),
    QtoTemplate('آبگرمکن/پکیج آبگرم', 'count'),
    QtoTemplate('منبع آب (ذخیره)', 'count'),
    QtoTemplate('پمپ آب', 'count'),
    QtoTemplate('دستگاه تصفیه آب', 'count'),
    QtoTemplate('کنتور آب', 'count'),
  ]),
  QtoCategory('sewage', 'فاضلاب', '🕳️', [
    QtoTemplate('لوله‌کشی فاضلاب (PVC)', 'length'),
    QtoTemplate('چاه فاضلاب/سپتیک', 'count'),
    QtoTemplate('کفشور', 'count'),
    QtoTemplate('سیفون/زانویی فاضلاب', 'count'),
    QtoTemplate('دریچه بازدید فاضلاب', 'count'),
  ]),
  QtoCategory('gas', 'گاز', '🔥', [
    QtoTemplate('لوله‌کشی گاز (فولادی/مسی)', 'length'),
    QtoTemplate('علمک گاز', 'count'),
    QtoTemplate('کنتور گاز', 'count'),
    QtoTemplate('شیر گاز قطع‌کن', 'count'),
  ]),
  QtoCategory('openings', 'درب و پنجره', '🚪', [
    QtoTemplate('درب داخلی چوبی', 'count'),
    QtoTemplate('درب ورودی واحد', 'count'),
    QtoTemplate('درب ورودی ساختمان', 'count'),
    QtoTemplate('درب ضدسرقت', 'count'),
    QtoTemplate('کرکره برقی پارکینگ', 'count'),
    QtoTemplate('پنجره آلومینیومی/UPVC', 'area'),
    QtoTemplate('شیشه دوجداره', 'area'),
    QtoTemplate('یراق‌آلات (دستگیره، قفل، لولا)', 'count'),
    QtoTemplate('کرکره/شاتر پنجره', 'area'),
    QtoTemplate('نرده و حفاظ', 'length'),
  ]),
  QtoCategory('hvac', 'سرمایش و گرمایش', '❄️', [
    QtoTemplate('رادیاتور', 'count'),
    QtoTemplate('لوله‌کشی بخاری/رادیاتور', 'length'),
    QtoTemplate('پکیج شوفاژ', 'count'),
    QtoTemplate('کولر آبی', 'count'),
    QtoTemplate('کولر گازی/اسپلیت', 'count'),
    QtoTemplate('داکت اسپلیت و کانال‌کشی', 'length'),
    QtoTemplate('فن کویل', 'count'),
    QtoTemplate('کف‌گرمایی (لوله‌کشی زیرکف)', 'area'),
    QtoTemplate('چیلر', 'count'),
    QtoTemplate('برج خنک‌کننده', 'count'),
  ]),
  QtoCategory('landscaping', 'محوطه‌سازی', '🌳', [
    QtoTemplate('آسفالت محوطه', 'area'),
    QtoTemplate('بتن‌ریزی محوطه', 'area'),
    QtoTemplate('جدول‌کشی', 'length'),
    QtoTemplate('فضای سبز/چمن‌کاری', 'area'),
    QtoTemplate('کفپوش پارکینگ', 'area'),
    QtoTemplate('نرده محوطه', 'length'),
    QtoTemplate('روشنایی محوطه (چراغ)', 'count'),
  ]),
  QtoCategory('elevator-safety', 'آسانسور و ایمنی', '🛗', [
    QtoTemplate('آسانسور مسافربری', 'count'),
    QtoTemplate('کپسول آتش‌نشانی', 'count'),
    QtoTemplate('سیستم اسپرینکلر', 'count'),
    QtoTemplate('هیدرانت آتش‌نشانی', 'count'),
    QtoTemplate('پله فرار/اضطراری', 'count'),
    QtoTemplate('چراغ اضطراری خروج', 'count'),
  ]),
];
